[package]
name = "tiny-render-rust"
version = "0.1.0"
authors = ["Darc <i@darc.pro>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
